services:
  oracle-12ee:
    image: oracle/database:12.2.0.1-ee
    container_name: oracle-12ee
    ports:
      - "1521:1521" # Puerto para Oracle Database
      - "5500:5500" # Puerto para Oracle Enterprise Manager Express(OEM express)
    environment:
      - ORACLE_PWD=pelota12 # Contraseña para el usuario SYS/SYSTEM
      - ORACLE_SID=BI
      - ORACLE_PDB=stage
      - ORACLE_CHARACTERSET=AL32UTF8
      - TZ=America/La_Paz
    volumes:
      - ./oradata:/opt/oracle/oradata # Para persistencia de datos
  biplatform:
    image: oracle/biplatform:12.2.1.3
    ports:
      - "9500:9500"
      - "9502:9502"
    environment:
      ADMIN_USERNAME: weblogic
      ADMIN_PASSWORD: orawl1234
      DB_HOST: oracle-12ee
      DB_PORT: 1521
      DB_SERVICE: STAGE
      DB_USERNAME: sys
      DB_PASSWORD: pelota12
      SCHEMA_PREFIX: DEV
      SCHEMA_PASSWORD: devPassword12
    depends_on:
      - oracle-12ee
    entrypoint: ["/bin/bash", "-c", "echo pelota12 | /u01/wait_for_db.sh /u01 sys oracle-12ee 1521 STAGE && /u01/createAndStartDomain.sh"]