services:
  oracle19ee:
    image: oracle/database:19.3.0-ee
    container_name: oracle19ee
    ports:
      - "1521:1521" # Puerto para Oracle Database
      - "5500:5500" # Puerto para Oracle Enterprise Manager
    environment:
      ORACLE_PDB: PDBACUARIO   # Nombre del pluggable database
      ORACLE_PWD: pelota12     # Contraseña para el usuario SYS/SYSTEM
      INIT_SGA_SIZE: 3000      # Tamaño de SGA (Shared Global Area) en MB
      INIT_PGA_SIZE: 1000      # Tamaño de PGA (Program Global Area) en MB
      ORACLE_CHARACTERSET: AL32UTF8
      TZ: America/La_Paz
      # - ENABLE_ARCHIVELOG=true  # Habilitar modo ARCHIVELOG
      # - ENABLE_FORCE_LOGGING=true # Habilitar FORCE LOGGING
    volumes:
      - ./oradata:/opt/oracle/oradata # Directorio para persistencia de datos
      - ./backup:/home/oracle/backup # Directorio para persistencia de datos
      # - ./archive_logs:/opt/oracle/oradata/ORCLCDB/archive_logs # Creo que no va ser necesario ya que el oradata engloba a esto.
    tmpfs:
      - /dev/shm:size=2g

    mem_limit: 8g
    cpus: 4.0
    mem_reservation: 6g

    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 8192
        hard: 8192

    restart: unless-stopped
    